//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.02 at 09:16:36 AM GMT 
//


package org.suggs.companydatafinderlib.companyinfo.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BbanDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BbanDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="bban_bank_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bban_branch_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bban_account" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bban_account_prefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bban_account_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bban_checksum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bban_currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bban_holder_kennitala" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bban_owner_number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bban_sort_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bban_zero" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BbanDetails", propOrder = {

})
public class BbanDetails {

    @XmlElement(name = "bban_bank_id")
    protected String bbanBankId;
    @XmlElement(name = "bban_branch_id")
    protected String bbanBranchId;
    @XmlElement(name = "bban_account")
    protected String bbanAccount;
    @XmlElement(name = "bban_account_prefix")
    protected String bbanAccountPrefix;
    @XmlElement(name = "bban_account_type")
    protected String bbanAccountType;
    @XmlElement(name = "bban_checksum")
    protected String bbanChecksum;
    @XmlElement(name = "bban_currency")
    protected String bbanCurrency;
    @XmlElement(name = "bban_holder_kennitala")
    protected String bbanHolderKennitala;
    @XmlElement(name = "bban_owner_number")
    protected String bbanOwnerNumber;
    @XmlElement(name = "bban_sort_code")
    protected String bbanSortCode;
    @XmlElement(name = "bban_zero")
    protected String bbanZero;

    /**
     * Gets the value of the bbanBankId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBbanBankId() {
        return bbanBankId;
    }

    /**
     * Sets the value of the bbanBankId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBbanBankId(String value) {
        this.bbanBankId = value;
    }

    /**
     * Gets the value of the bbanBranchId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBbanBranchId() {
        return bbanBranchId;
    }

    /**
     * Sets the value of the bbanBranchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBbanBranchId(String value) {
        this.bbanBranchId = value;
    }

    /**
     * Gets the value of the bbanAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBbanAccount() {
        return bbanAccount;
    }

    /**
     * Sets the value of the bbanAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBbanAccount(String value) {
        this.bbanAccount = value;
    }

    /**
     * Gets the value of the bbanAccountPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBbanAccountPrefix() {
        return bbanAccountPrefix;
    }

    /**
     * Sets the value of the bbanAccountPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBbanAccountPrefix(String value) {
        this.bbanAccountPrefix = value;
    }

    /**
     * Gets the value of the bbanAccountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBbanAccountType() {
        return bbanAccountType;
    }

    /**
     * Sets the value of the bbanAccountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBbanAccountType(String value) {
        this.bbanAccountType = value;
    }

    /**
     * Gets the value of the bbanChecksum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBbanChecksum() {
        return bbanChecksum;
    }

    /**
     * Sets the value of the bbanChecksum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBbanChecksum(String value) {
        this.bbanChecksum = value;
    }

    /**
     * Gets the value of the bbanCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBbanCurrency() {
        return bbanCurrency;
    }

    /**
     * Sets the value of the bbanCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBbanCurrency(String value) {
        this.bbanCurrency = value;
    }

    /**
     * Gets the value of the bbanHolderKennitala property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBbanHolderKennitala() {
        return bbanHolderKennitala;
    }

    /**
     * Sets the value of the bbanHolderKennitala property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBbanHolderKennitala(String value) {
        this.bbanHolderKennitala = value;
    }

    /**
     * Gets the value of the bbanOwnerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBbanOwnerNumber() {
        return bbanOwnerNumber;
    }

    /**
     * Sets the value of the bbanOwnerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBbanOwnerNumber(String value) {
        this.bbanOwnerNumber = value;
    }

    /**
     * Gets the value of the bbanSortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBbanSortCode() {
        return bbanSortCode;
    }

    /**
     * Sets the value of the bbanSortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBbanSortCode(String value) {
        this.bbanSortCode = value;
    }

    /**
     * Gets the value of the bbanZero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBbanZero() {
        return bbanZero;
    }

    /**
     * Sets the value of the bbanZero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBbanZero(String value) {
        this.bbanZero = value;
    }

}
