//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.02 at 09:16:36 AM GMT 
//


package org.suggs.companydatafinderlib.companyinfo.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BerichtObjectDocumentResultaat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BerichtObjectDocumentResultaat">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="overzicht" type="{http://www.webservices.nl/soap/}DocumentOverzicht" minOccurs="0"/>
 *         &lt;element name="eigendomsbericht" type="{http://www.webservices.nl/soap/}BerichtObjectDocument" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BerichtObjectDocumentResultaat", propOrder = {

})
public class BerichtObjectDocumentResultaat {

    protected DocumentOverzicht overzicht;
    protected BerichtObjectDocument eigendomsbericht;

    /**
     * Gets the value of the overzicht property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentOverzicht }
     *     
     */
    public DocumentOverzicht getOverzicht() {
        return overzicht;
    }

    /**
     * Sets the value of the overzicht property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentOverzicht }
     *     
     */
    public void setOverzicht(DocumentOverzicht value) {
        this.overzicht = value;
    }

    /**
     * Gets the value of the eigendomsbericht property.
     * 
     * @return
     *     possible object is
     *     {@link BerichtObjectDocument }
     *     
     */
    public BerichtObjectDocument getEigendomsbericht() {
        return eigendomsbericht;
    }

    /**
     * Sets the value of the eigendomsbericht property.
     * 
     * @param value
     *     allowed object is
     *     {@link BerichtObjectDocument }
     *     
     */
    public void setEigendomsbericht(BerichtObjectDocument value) {
        this.eigendomsbericht = value;
    }

}
