//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.02 at 09:16:36 AM GMT 
//


package org.suggs.companydatafinderlib.companyinfo.wsdl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplianceBusiness complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplianceBusiness">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="compliance_business_id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="business_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="website_url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="telephone_number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fax_number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sanctions" type="{http://www.webservices.nl/soap/}ComplianceSanctionReferenceArray"/>
 *         &lt;element name="flags" type="{http://www.webservices.nl/soap/}stringArray"/>
 *         &lt;element name="aliases" type="{http://www.webservices.nl/soap/}stringArray"/>
 *         &lt;element name="addresses" type="{http://www.webservices.nl/soap/}ComplianceAddressReferenceArray"/>
 *         &lt;element name="related_businesses" type="{http://www.webservices.nl/soap/}ComplianceBusinessReferenceArray"/>
 *         &lt;element name="related_persons" type="{http://www.webservices.nl/soap/}CompliancePersonReferenceArray"/>
 *         &lt;element name="notes" type="{http://www.webservices.nl/soap/}ComplianceNoteReferenceArray"/>
 *         &lt;element name="documents" type="{http://www.webservices.nl/soap/}ComplianceDocumentReferenceArray"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplianceBusiness", propOrder = {

})
public class ComplianceBusiness {

    @XmlElement(name = "compliance_business_id", required = true)
    protected BigInteger complianceBusinessId;
    @XmlElement(name = "business_name", required = true)
    protected String businessName;
    @XmlElement(name = "website_url")
    protected String websiteUrl;
    @XmlElement(name = "telephone_number")
    protected String telephoneNumber;
    @XmlElement(name = "fax_number")
    protected String faxNumber;
    @XmlElement(required = true)
    protected ComplianceSanctionReferenceArray sanctions;
    @XmlElement(required = true)
    protected StringArray flags;
    @XmlElement(required = true)
    protected StringArray aliases;
    @XmlElement(required = true)
    protected ComplianceAddressReferenceArray addresses;
    @XmlElement(name = "related_businesses", required = true)
    protected ComplianceBusinessReferenceArray relatedBusinesses;
    @XmlElement(name = "related_persons", required = true)
    protected CompliancePersonReferenceArray relatedPersons;
    @XmlElement(required = true)
    protected ComplianceNoteReferenceArray notes;
    @XmlElement(required = true)
    protected ComplianceDocumentReferenceArray documents;

    /**
     * Gets the value of the complianceBusinessId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getComplianceBusinessId() {
        return complianceBusinessId;
    }

    /**
     * Sets the value of the complianceBusinessId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setComplianceBusinessId(BigInteger value) {
        this.complianceBusinessId = value;
    }

    /**
     * Gets the value of the businessName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * Sets the value of the businessName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessName(String value) {
        this.businessName = value;
    }

    /**
     * Gets the value of the websiteUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebsiteUrl() {
        return websiteUrl;
    }

    /**
     * Sets the value of the websiteUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebsiteUrl(String value) {
        this.websiteUrl = value;
    }

    /**
     * Gets the value of the telephoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelephoneNumber() {
        return telephoneNumber;
    }

    /**
     * Sets the value of the telephoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelephoneNumber(String value) {
        this.telephoneNumber = value;
    }

    /**
     * Gets the value of the faxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxNumber() {
        return faxNumber;
    }

    /**
     * Sets the value of the faxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxNumber(String value) {
        this.faxNumber = value;
    }

    /**
     * Gets the value of the sanctions property.
     * 
     * @return
     *     possible object is
     *     {@link ComplianceSanctionReferenceArray }
     *     
     */
    public ComplianceSanctionReferenceArray getSanctions() {
        return sanctions;
    }

    /**
     * Sets the value of the sanctions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplianceSanctionReferenceArray }
     *     
     */
    public void setSanctions(ComplianceSanctionReferenceArray value) {
        this.sanctions = value;
    }

    /**
     * Gets the value of the flags property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getFlags() {
        return flags;
    }

    /**
     * Sets the value of the flags property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setFlags(StringArray value) {
        this.flags = value;
    }

    /**
     * Gets the value of the aliases property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getAliases() {
        return aliases;
    }

    /**
     * Sets the value of the aliases property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setAliases(StringArray value) {
        this.aliases = value;
    }

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link ComplianceAddressReferenceArray }
     *     
     */
    public ComplianceAddressReferenceArray getAddresses() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplianceAddressReferenceArray }
     *     
     */
    public void setAddresses(ComplianceAddressReferenceArray value) {
        this.addresses = value;
    }

    /**
     * Gets the value of the relatedBusinesses property.
     * 
     * @return
     *     possible object is
     *     {@link ComplianceBusinessReferenceArray }
     *     
     */
    public ComplianceBusinessReferenceArray getRelatedBusinesses() {
        return relatedBusinesses;
    }

    /**
     * Sets the value of the relatedBusinesses property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplianceBusinessReferenceArray }
     *     
     */
    public void setRelatedBusinesses(ComplianceBusinessReferenceArray value) {
        this.relatedBusinesses = value;
    }

    /**
     * Gets the value of the relatedPersons property.
     * 
     * @return
     *     possible object is
     *     {@link CompliancePersonReferenceArray }
     *     
     */
    public CompliancePersonReferenceArray getRelatedPersons() {
        return relatedPersons;
    }

    /**
     * Sets the value of the relatedPersons property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompliancePersonReferenceArray }
     *     
     */
    public void setRelatedPersons(CompliancePersonReferenceArray value) {
        this.relatedPersons = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link ComplianceNoteReferenceArray }
     *     
     */
    public ComplianceNoteReferenceArray getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplianceNoteReferenceArray }
     *     
     */
    public void setNotes(ComplianceNoteReferenceArray value) {
        this.notes = value;
    }

    /**
     * Gets the value of the documents property.
     * 
     * @return
     *     possible object is
     *     {@link ComplianceDocumentReferenceArray }
     *     
     */
    public ComplianceDocumentReferenceArray getDocuments() {
        return documents;
    }

    /**
     * Sets the value of the documents property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplianceDocumentReferenceArray }
     *     
     */
    public void setDocuments(ComplianceDocumentReferenceArray value) {
        this.documents = value;
    }

}
