//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.02 at 09:16:36 AM GMT 
//


package org.suggs.companydatafinderlib.companyinfo.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreditsafeCompanyNegativeInformationNLV2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditsafeCompanyNegativeInformationNLV2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="court_items" type="{http://www.webservices.nl/soap/}CreditsafeCompanyNegativeInformationNLCourtItemV2Array" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditsafeCompanyNegativeInformationNLV2", propOrder = {

})
public class CreditsafeCompanyNegativeInformationNLV2 {

    @XmlElement(name = "court_items")
    protected CreditsafeCompanyNegativeInformationNLCourtItemV2Array courtItems;

    /**
     * Gets the value of the courtItems property.
     * 
     * @return
     *     possible object is
     *     {@link CreditsafeCompanyNegativeInformationNLCourtItemV2Array }
     *     
     */
    public CreditsafeCompanyNegativeInformationNLCourtItemV2Array getCourtItems() {
        return courtItems;
    }

    /**
     * Sets the value of the courtItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditsafeCompanyNegativeInformationNLCourtItemV2Array }
     *     
     */
    public void setCourtItems(CreditsafeCompanyNegativeInformationNLCourtItemV2Array value) {
        this.courtItems = value;
    }

}
