//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.02 at 09:16:36 AM GMT 
//


package org.suggs.companydatafinderlib.companyinfo.wsdl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CreditsafeCompanyAdditionalInformationNLLetterOfLiabilityInformation403V2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditsafeCompanyAdditionalInformationNLLetterOfLiabilityInformation403V2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="financial_year" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="company_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="company_number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="date_submitted" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="letter_of_liability1_start_date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="letter_of_liability1_submitted_date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="letter_of_liability1_removal_submitted" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="letter_of_liability1_removal_date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="letter_of_liability2_start_date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="letter_of_liability2_submitted_date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="letter_of_liability2_removal_submitted" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="letter_of_liability2_removal_date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="letter_of_liability1_start_date_parent2" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="letter_of_liability1_submitted_date_parent2" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="letter_of_liability1_removal_submitted_parent2" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="letter_of_liability1_removal_date_parent2" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="letter_of_liability2_start_date_parent2" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="letter_of_liability2_submitted_date_parent2" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="letter_of_liability2_removal_submitted_parent2" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="letter_of_liability2_removal_date_parent2" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditsafeCompanyAdditionalInformationNLLetterOfLiabilityInformation403V2", propOrder = {

})
public class CreditsafeCompanyAdditionalInformationNLLetterOfLiabilityInformation403V2 {

    @XmlElement(name = "financial_year")
    protected BigInteger financialYear;
    @XmlElement(name = "company_name")
    protected String companyName;
    @XmlElement(name = "company_number")
    protected String companyNumber;
    @XmlElement(name = "date_submitted")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateSubmitted;
    @XmlElement(name = "letter_of_liability1_start_date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar letterOfLiability1StartDate;
    @XmlElement(name = "letter_of_liability1_submitted_date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar letterOfLiability1SubmittedDate;
    @XmlElement(name = "letter_of_liability1_removal_submitted")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar letterOfLiability1RemovalSubmitted;
    @XmlElement(name = "letter_of_liability1_removal_date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar letterOfLiability1RemovalDate;
    @XmlElement(name = "letter_of_liability2_start_date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar letterOfLiability2StartDate;
    @XmlElement(name = "letter_of_liability2_submitted_date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar letterOfLiability2SubmittedDate;
    @XmlElement(name = "letter_of_liability2_removal_submitted")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar letterOfLiability2RemovalSubmitted;
    @XmlElement(name = "letter_of_liability2_removal_date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar letterOfLiability2RemovalDate;
    @XmlElement(name = "letter_of_liability1_start_date_parent2")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar letterOfLiability1StartDateParent2;
    @XmlElement(name = "letter_of_liability1_submitted_date_parent2")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar letterOfLiability1SubmittedDateParent2;
    @XmlElement(name = "letter_of_liability1_removal_submitted_parent2")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar letterOfLiability1RemovalSubmittedParent2;
    @XmlElement(name = "letter_of_liability1_removal_date_parent2")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar letterOfLiability1RemovalDateParent2;
    @XmlElement(name = "letter_of_liability2_start_date_parent2")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar letterOfLiability2StartDateParent2;
    @XmlElement(name = "letter_of_liability2_submitted_date_parent2")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar letterOfLiability2SubmittedDateParent2;
    @XmlElement(name = "letter_of_liability2_removal_submitted_parent2")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar letterOfLiability2RemovalSubmittedParent2;
    @XmlElement(name = "letter_of_liability2_removal_date_parent2")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar letterOfLiability2RemovalDateParent2;

    /**
     * Gets the value of the financialYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFinancialYear() {
        return financialYear;
    }

    /**
     * Sets the value of the financialYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFinancialYear(BigInteger value) {
        this.financialYear = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the companyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyNumber() {
        return companyNumber;
    }

    /**
     * Sets the value of the companyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyNumber(String value) {
        this.companyNumber = value;
    }

    /**
     * Gets the value of the dateSubmitted property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateSubmitted() {
        return dateSubmitted;
    }

    /**
     * Sets the value of the dateSubmitted property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateSubmitted(XMLGregorianCalendar value) {
        this.dateSubmitted = value;
    }

    /**
     * Gets the value of the letterOfLiability1StartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLetterOfLiability1StartDate() {
        return letterOfLiability1StartDate;
    }

    /**
     * Sets the value of the letterOfLiability1StartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLetterOfLiability1StartDate(XMLGregorianCalendar value) {
        this.letterOfLiability1StartDate = value;
    }

    /**
     * Gets the value of the letterOfLiability1SubmittedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLetterOfLiability1SubmittedDate() {
        return letterOfLiability1SubmittedDate;
    }

    /**
     * Sets the value of the letterOfLiability1SubmittedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLetterOfLiability1SubmittedDate(XMLGregorianCalendar value) {
        this.letterOfLiability1SubmittedDate = value;
    }

    /**
     * Gets the value of the letterOfLiability1RemovalSubmitted property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLetterOfLiability1RemovalSubmitted() {
        return letterOfLiability1RemovalSubmitted;
    }

    /**
     * Sets the value of the letterOfLiability1RemovalSubmitted property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLetterOfLiability1RemovalSubmitted(XMLGregorianCalendar value) {
        this.letterOfLiability1RemovalSubmitted = value;
    }

    /**
     * Gets the value of the letterOfLiability1RemovalDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLetterOfLiability1RemovalDate() {
        return letterOfLiability1RemovalDate;
    }

    /**
     * Sets the value of the letterOfLiability1RemovalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLetterOfLiability1RemovalDate(XMLGregorianCalendar value) {
        this.letterOfLiability1RemovalDate = value;
    }

    /**
     * Gets the value of the letterOfLiability2StartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLetterOfLiability2StartDate() {
        return letterOfLiability2StartDate;
    }

    /**
     * Sets the value of the letterOfLiability2StartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLetterOfLiability2StartDate(XMLGregorianCalendar value) {
        this.letterOfLiability2StartDate = value;
    }

    /**
     * Gets the value of the letterOfLiability2SubmittedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLetterOfLiability2SubmittedDate() {
        return letterOfLiability2SubmittedDate;
    }

    /**
     * Sets the value of the letterOfLiability2SubmittedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLetterOfLiability2SubmittedDate(XMLGregorianCalendar value) {
        this.letterOfLiability2SubmittedDate = value;
    }

    /**
     * Gets the value of the letterOfLiability2RemovalSubmitted property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLetterOfLiability2RemovalSubmitted() {
        return letterOfLiability2RemovalSubmitted;
    }

    /**
     * Sets the value of the letterOfLiability2RemovalSubmitted property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLetterOfLiability2RemovalSubmitted(XMLGregorianCalendar value) {
        this.letterOfLiability2RemovalSubmitted = value;
    }

    /**
     * Gets the value of the letterOfLiability2RemovalDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLetterOfLiability2RemovalDate() {
        return letterOfLiability2RemovalDate;
    }

    /**
     * Sets the value of the letterOfLiability2RemovalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLetterOfLiability2RemovalDate(XMLGregorianCalendar value) {
        this.letterOfLiability2RemovalDate = value;
    }

    /**
     * Gets the value of the letterOfLiability1StartDateParent2 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLetterOfLiability1StartDateParent2() {
        return letterOfLiability1StartDateParent2;
    }

    /**
     * Sets the value of the letterOfLiability1StartDateParent2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLetterOfLiability1StartDateParent2(XMLGregorianCalendar value) {
        this.letterOfLiability1StartDateParent2 = value;
    }

    /**
     * Gets the value of the letterOfLiability1SubmittedDateParent2 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLetterOfLiability1SubmittedDateParent2() {
        return letterOfLiability1SubmittedDateParent2;
    }

    /**
     * Sets the value of the letterOfLiability1SubmittedDateParent2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLetterOfLiability1SubmittedDateParent2(XMLGregorianCalendar value) {
        this.letterOfLiability1SubmittedDateParent2 = value;
    }

    /**
     * Gets the value of the letterOfLiability1RemovalSubmittedParent2 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLetterOfLiability1RemovalSubmittedParent2() {
        return letterOfLiability1RemovalSubmittedParent2;
    }

    /**
     * Sets the value of the letterOfLiability1RemovalSubmittedParent2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLetterOfLiability1RemovalSubmittedParent2(XMLGregorianCalendar value) {
        this.letterOfLiability1RemovalSubmittedParent2 = value;
    }

    /**
     * Gets the value of the letterOfLiability1RemovalDateParent2 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLetterOfLiability1RemovalDateParent2() {
        return letterOfLiability1RemovalDateParent2;
    }

    /**
     * Sets the value of the letterOfLiability1RemovalDateParent2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLetterOfLiability1RemovalDateParent2(XMLGregorianCalendar value) {
        this.letterOfLiability1RemovalDateParent2 = value;
    }

    /**
     * Gets the value of the letterOfLiability2StartDateParent2 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLetterOfLiability2StartDateParent2() {
        return letterOfLiability2StartDateParent2;
    }

    /**
     * Sets the value of the letterOfLiability2StartDateParent2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLetterOfLiability2StartDateParent2(XMLGregorianCalendar value) {
        this.letterOfLiability2StartDateParent2 = value;
    }

    /**
     * Gets the value of the letterOfLiability2SubmittedDateParent2 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLetterOfLiability2SubmittedDateParent2() {
        return letterOfLiability2SubmittedDateParent2;
    }

    /**
     * Sets the value of the letterOfLiability2SubmittedDateParent2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLetterOfLiability2SubmittedDateParent2(XMLGregorianCalendar value) {
        this.letterOfLiability2SubmittedDateParent2 = value;
    }

    /**
     * Gets the value of the letterOfLiability2RemovalSubmittedParent2 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLetterOfLiability2RemovalSubmittedParent2() {
        return letterOfLiability2RemovalSubmittedParent2;
    }

    /**
     * Sets the value of the letterOfLiability2RemovalSubmittedParent2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLetterOfLiability2RemovalSubmittedParent2(XMLGregorianCalendar value) {
        this.letterOfLiability2RemovalSubmittedParent2 = value;
    }

    /**
     * Gets the value of the letterOfLiability2RemovalDateParent2 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLetterOfLiability2RemovalDateParent2() {
        return letterOfLiability2RemovalDateParent2;
    }

    /**
     * Sets the value of the letterOfLiability2RemovalDateParent2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLetterOfLiability2RemovalDateParent2(XMLGregorianCalendar value) {
        this.letterOfLiability2RemovalDateParent2 = value;
    }

}
