//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.02 at 09:16:36 AM GMT 
//


package org.suggs.companydatafinderlib.companyinfo.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreditsafeCompanyShareCapitalStructureV2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditsafeCompanyShareCapitalStructureV2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="issued_share_capital" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nominal_share_capital" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="share_holders" type="{http://www.webservices.nl/soap/}CreditsafeCompanyShareHolderV2Array" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditsafeCompanyShareCapitalStructureV2", propOrder = {

})
public class CreditsafeCompanyShareCapitalStructureV2 {

    @XmlElement(name = "issued_share_capital")
    protected String issuedShareCapital;
    @XmlElement(name = "nominal_share_capital")
    protected String nominalShareCapital;
    @XmlElement(name = "share_holders")
    protected CreditsafeCompanyShareHolderV2Array shareHolders;

    /**
     * Gets the value of the issuedShareCapital property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuedShareCapital() {
        return issuedShareCapital;
    }

    /**
     * Sets the value of the issuedShareCapital property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuedShareCapital(String value) {
        this.issuedShareCapital = value;
    }

    /**
     * Gets the value of the nominalShareCapital property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNominalShareCapital() {
        return nominalShareCapital;
    }

    /**
     * Sets the value of the nominalShareCapital property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNominalShareCapital(String value) {
        this.nominalShareCapital = value;
    }

    /**
     * Gets the value of the shareHolders property.
     * 
     * @return
     *     possible object is
     *     {@link CreditsafeCompanyShareHolderV2Array }
     *     
     */
    public CreditsafeCompanyShareHolderV2Array getShareHolders() {
        return shareHolders;
    }

    /**
     * Sets the value of the shareHolders property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditsafeCompanyShareHolderV2Array }
     *     
     */
    public void setShareHolders(CreditsafeCompanyShareHolderV2Array value) {
        this.shareHolders = value;
    }

}
