//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.02 at 09:16:36 AM GMT 
//


package org.suggs.companydatafinderlib.companyinfo.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dutchBusinessSearchSelectionSimpleRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dutchBusinessSearchSelectionSimpleRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="city" type="{http://www.webservices.nl/soap/}stringArray"/>
 *         &lt;element name="postcode" type="{http://www.webservices.nl/soap/}stringArray"/>
 *         &lt;element name="sbi" type="{http://www.webservices.nl/soap/}stringArray"/>
 *         &lt;element name="primary_sbi_only" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="legal_form" type="{http://www.webservices.nl/soap/}intArray"/>
 *         &lt;element name="employees_min" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="employees_max" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="economically_active" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="financial_status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="changed_since" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="new_since" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="page" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="provinces" type="{http://www.webservices.nl/soap/}stringArray"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dutchBusinessSearchSelectionSimpleRequestType", propOrder = {

})
public class DutchBusinessSearchSelectionSimpleRequestType {

    @XmlElement(required = true)
    protected StringArray city;
    @XmlElement(required = true)
    protected StringArray postcode;
    @XmlElement(required = true)
    protected StringArray sbi;
    @XmlElement(name = "primary_sbi_only")
    protected boolean primarySbiOnly;
    @XmlElement(name = "legal_form", required = true)
    protected IntArray legalForm;
    @XmlElement(name = "employees_min")
    protected int employeesMin;
    @XmlElement(name = "employees_max")
    protected int employeesMax;
    @XmlElement(name = "economically_active", required = true)
    protected String economicallyActive;
    @XmlElement(name = "financial_status", required = true)
    protected String financialStatus;
    @XmlElement(name = "changed_since", required = true)
    protected String changedSince;
    @XmlElement(name = "new_since", required = true)
    protected String newSince;
    protected int page;
    @XmlElement(required = true)
    protected StringArray provinces;

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setCity(StringArray value) {
        this.city = value;
    }

    /**
     * Gets the value of the postcode property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getPostcode() {
        return postcode;
    }

    /**
     * Sets the value of the postcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setPostcode(StringArray value) {
        this.postcode = value;
    }

    /**
     * Gets the value of the sbi property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getSbi() {
        return sbi;
    }

    /**
     * Sets the value of the sbi property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setSbi(StringArray value) {
        this.sbi = value;
    }

    /**
     * Gets the value of the primarySbiOnly property.
     * 
     */
    public boolean isPrimarySbiOnly() {
        return primarySbiOnly;
    }

    /**
     * Sets the value of the primarySbiOnly property.
     * 
     */
    public void setPrimarySbiOnly(boolean value) {
        this.primarySbiOnly = value;
    }

    /**
     * Gets the value of the legalForm property.
     * 
     * @return
     *     possible object is
     *     {@link IntArray }
     *     
     */
    public IntArray getLegalForm() {
        return legalForm;
    }

    /**
     * Sets the value of the legalForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntArray }
     *     
     */
    public void setLegalForm(IntArray value) {
        this.legalForm = value;
    }

    /**
     * Gets the value of the employeesMin property.
     * 
     */
    public int getEmployeesMin() {
        return employeesMin;
    }

    /**
     * Sets the value of the employeesMin property.
     * 
     */
    public void setEmployeesMin(int value) {
        this.employeesMin = value;
    }

    /**
     * Gets the value of the employeesMax property.
     * 
     */
    public int getEmployeesMax() {
        return employeesMax;
    }

    /**
     * Sets the value of the employeesMax property.
     * 
     */
    public void setEmployeesMax(int value) {
        this.employeesMax = value;
    }

    /**
     * Gets the value of the economicallyActive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEconomicallyActive() {
        return economicallyActive;
    }

    /**
     * Sets the value of the economicallyActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEconomicallyActive(String value) {
        this.economicallyActive = value;
    }

    /**
     * Gets the value of the financialStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinancialStatus() {
        return financialStatus;
    }

    /**
     * Sets the value of the financialStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinancialStatus(String value) {
        this.financialStatus = value;
    }

    /**
     * Gets the value of the changedSince property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangedSince() {
        return changedSince;
    }

    /**
     * Sets the value of the changedSince property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangedSince(String value) {
        this.changedSince = value;
    }

    /**
     * Gets the value of the newSince property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewSince() {
        return newSince;
    }

    /**
     * Sets the value of the newSince property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewSince(String value) {
        this.newSince = value;
    }

    /**
     * Gets the value of the page property.
     * 
     */
    public int getPage() {
        return page;
    }

    /**
     * Sets the value of the page property.
     * 
     */
    public void setPage(int value) {
        this.page = value;
    }

    /**
     * Gets the value of the provinces property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getProvinces() {
        return provinces;
    }

    /**
     * Sets the value of the provinces property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setProvinces(StringArray value) {
        this.provinces = value;
    }

}
