//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.02 at 09:16:36 AM GMT 
//


package org.suggs.companydatafinderlib.companyinfo.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DutchBusinessUBOClassificationResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DutchBusinessUBOClassificationResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="token" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scenario" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="suspects" type="{http://www.webservices.nl/soap/}DutchBusinessUBOClassifiedSuspectArray"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DutchBusinessUBOClassificationResult", propOrder = {

})
public class DutchBusinessUBOClassificationResult {

    @XmlElement(required = true)
    protected String token;
    @XmlElement(required = true)
    protected String scenario;
    @XmlElement(required = true)
    protected DutchBusinessUBOClassifiedSuspectArray suspects;

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

    /**
     * Gets the value of the scenario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScenario() {
        return scenario;
    }

    /**
     * Sets the value of the scenario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScenario(String value) {
        this.scenario = value;
    }

    /**
     * Gets the value of the suspects property.
     * 
     * @return
     *     possible object is
     *     {@link DutchBusinessUBOClassifiedSuspectArray }
     *     
     */
    public DutchBusinessUBOClassifiedSuspectArray getSuspects() {
        return suspects;
    }

    /**
     * Sets the value of the suspects property.
     * 
     * @param value
     *     allowed object is
     *     {@link DutchBusinessUBOClassifiedSuspectArray }
     *     
     */
    public void setSuspects(DutchBusinessUBOClassifiedSuspectArray value) {
        this.suspects = value;
    }

}
