//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.02 at 09:16:36 AM GMT 
//


package org.suggs.companydatafinderlib.companyinfo.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KadasterV2KadastraleGrootte complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KadasterV2KadastraleGrootte">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="waarde" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="soort_grootte" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KadasterV2KadastraleGrootte", propOrder = {

})
public class KadasterV2KadastraleGrootte {

    protected Float waarde;
    @XmlElement(name = "soort_grootte")
    protected String soortGrootte;

    /**
     * Gets the value of the waarde property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getWaarde() {
        return waarde;
    }

    /**
     * Sets the value of the waarde property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setWaarde(Float value) {
        this.waarde = value;
    }

    /**
     * Gets the value of the soortGrootte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoortGrootte() {
        return soortGrootte;
    }

    /**
     * Sets the value of the soortGrootte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoortGrootte(String value) {
        this.soortGrootte = value;
    }

}
