//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.02 at 09:16:36 AM GMT 
//


package org.suggs.companydatafinderlib.companyinfo.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for KadasterV2NatuurlijkPersoon complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KadasterV2NatuurlijkPersoon">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="identificatie" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="indicatie_beschikkingsbevoegdheid" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="bsn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="aanduiding_naamgebruik" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="adellijke_titel_of_predikaat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="voorletters" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="voornamen" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="voorvoegsel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="geslachtnaam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="geslacht" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="datum_geboorte" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="indicatie_overleden" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="datum_overlijden" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="land_waarnaar_vertrokken" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bpr_gekoppeld" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="burgerlijke_staat_omschrijving" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="postlocatie" type="{http://www.webservices.nl/soap/}KadasterV2AdresLocatie" minOccurs="0"/>
 *         &lt;element name="woonlocatie" type="{http://www.webservices.nl/soap/}KadasterV2AdresLocatie" minOccurs="0"/>
 *         &lt;element name="vermeld_in" type="{http://www.webservices.nl/soap/}KadasterV2StukdeelArray" minOccurs="0"/>
 *         &lt;element name="aanvullingen" type="{http://www.webservices.nl/soap/}KadasterV2AanvullingArray" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KadasterV2NatuurlijkPersoon", propOrder = {

})
public class KadasterV2NatuurlijkPersoon {

    @XmlElement(required = true)
    protected String identificatie;
    @XmlElement(name = "indicatie_beschikkingsbevoegdheid")
    protected Boolean indicatieBeschikkingsbevoegdheid;
    protected String bsn;
    @XmlElement(name = "aanduiding_naamgebruik")
    protected String aanduidingNaamgebruik;
    @XmlElement(name = "adellijke_titel_of_predikaat")
    protected String adellijkeTitelOfPredikaat;
    protected String voorletters;
    protected String voornamen;
    protected String voorvoegsel;
    protected String geslachtnaam;
    protected String geslacht;
    @XmlElement(name = "datum_geboorte")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumGeboorte;
    @XmlElement(name = "indicatie_overleden")
    protected Boolean indicatieOverleden;
    @XmlElement(name = "datum_overlijden")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumOverlijden;
    @XmlElement(name = "land_waarnaar_vertrokken")
    protected String landWaarnaarVertrokken;
    @XmlElement(name = "bpr_gekoppeld")
    protected Boolean bprGekoppeld;
    @XmlElement(name = "burgerlijke_staat_omschrijving")
    protected String burgerlijkeStaatOmschrijving;
    protected KadasterV2AdresLocatie postlocatie;
    protected KadasterV2AdresLocatie woonlocatie;
    @XmlElement(name = "vermeld_in")
    protected KadasterV2StukdeelArray vermeldIn;
    protected KadasterV2AanvullingArray aanvullingen;

    /**
     * Gets the value of the identificatie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificatie() {
        return identificatie;
    }

    /**
     * Sets the value of the identificatie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificatie(String value) {
        this.identificatie = value;
    }

    /**
     * Gets the value of the indicatieBeschikkingsbevoegdheid property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIndicatieBeschikkingsbevoegdheid() {
        return indicatieBeschikkingsbevoegdheid;
    }

    /**
     * Sets the value of the indicatieBeschikkingsbevoegdheid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIndicatieBeschikkingsbevoegdheid(Boolean value) {
        this.indicatieBeschikkingsbevoegdheid = value;
    }

    /**
     * Gets the value of the bsn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBsn() {
        return bsn;
    }

    /**
     * Sets the value of the bsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBsn(String value) {
        this.bsn = value;
    }

    /**
     * Gets the value of the aanduidingNaamgebruik property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAanduidingNaamgebruik() {
        return aanduidingNaamgebruik;
    }

    /**
     * Sets the value of the aanduidingNaamgebruik property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAanduidingNaamgebruik(String value) {
        this.aanduidingNaamgebruik = value;
    }

    /**
     * Gets the value of the adellijkeTitelOfPredikaat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdellijkeTitelOfPredikaat() {
        return adellijkeTitelOfPredikaat;
    }

    /**
     * Sets the value of the adellijkeTitelOfPredikaat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdellijkeTitelOfPredikaat(String value) {
        this.adellijkeTitelOfPredikaat = value;
    }

    /**
     * Gets the value of the voorletters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoorletters() {
        return voorletters;
    }

    /**
     * Sets the value of the voorletters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoorletters(String value) {
        this.voorletters = value;
    }

    /**
     * Gets the value of the voornamen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoornamen() {
        return voornamen;
    }

    /**
     * Sets the value of the voornamen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoornamen(String value) {
        this.voornamen = value;
    }

    /**
     * Gets the value of the voorvoegsel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoorvoegsel() {
        return voorvoegsel;
    }

    /**
     * Sets the value of the voorvoegsel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoorvoegsel(String value) {
        this.voorvoegsel = value;
    }

    /**
     * Gets the value of the geslachtnaam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeslachtnaam() {
        return geslachtnaam;
    }

    /**
     * Sets the value of the geslachtnaam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeslachtnaam(String value) {
        this.geslachtnaam = value;
    }

    /**
     * Gets the value of the geslacht property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeslacht() {
        return geslacht;
    }

    /**
     * Sets the value of the geslacht property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeslacht(String value) {
        this.geslacht = value;
    }

    /**
     * Gets the value of the datumGeboorte property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumGeboorte() {
        return datumGeboorte;
    }

    /**
     * Sets the value of the datumGeboorte property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumGeboorte(XMLGregorianCalendar value) {
        this.datumGeboorte = value;
    }

    /**
     * Gets the value of the indicatieOverleden property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIndicatieOverleden() {
        return indicatieOverleden;
    }

    /**
     * Sets the value of the indicatieOverleden property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIndicatieOverleden(Boolean value) {
        this.indicatieOverleden = value;
    }

    /**
     * Gets the value of the datumOverlijden property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumOverlijden() {
        return datumOverlijden;
    }

    /**
     * Sets the value of the datumOverlijden property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumOverlijden(XMLGregorianCalendar value) {
        this.datumOverlijden = value;
    }

    /**
     * Gets the value of the landWaarnaarVertrokken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLandWaarnaarVertrokken() {
        return landWaarnaarVertrokken;
    }

    /**
     * Sets the value of the landWaarnaarVertrokken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLandWaarnaarVertrokken(String value) {
        this.landWaarnaarVertrokken = value;
    }

    /**
     * Gets the value of the bprGekoppeld property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBprGekoppeld() {
        return bprGekoppeld;
    }

    /**
     * Sets the value of the bprGekoppeld property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBprGekoppeld(Boolean value) {
        this.bprGekoppeld = value;
    }

    /**
     * Gets the value of the burgerlijkeStaatOmschrijving property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBurgerlijkeStaatOmschrijving() {
        return burgerlijkeStaatOmschrijving;
    }

    /**
     * Sets the value of the burgerlijkeStaatOmschrijving property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBurgerlijkeStaatOmschrijving(String value) {
        this.burgerlijkeStaatOmschrijving = value;
    }

    /**
     * Gets the value of the postlocatie property.
     * 
     * @return
     *     possible object is
     *     {@link KadasterV2AdresLocatie }
     *     
     */
    public KadasterV2AdresLocatie getPostlocatie() {
        return postlocatie;
    }

    /**
     * Sets the value of the postlocatie property.
     * 
     * @param value
     *     allowed object is
     *     {@link KadasterV2AdresLocatie }
     *     
     */
    public void setPostlocatie(KadasterV2AdresLocatie value) {
        this.postlocatie = value;
    }

    /**
     * Gets the value of the woonlocatie property.
     * 
     * @return
     *     possible object is
     *     {@link KadasterV2AdresLocatie }
     *     
     */
    public KadasterV2AdresLocatie getWoonlocatie() {
        return woonlocatie;
    }

    /**
     * Sets the value of the woonlocatie property.
     * 
     * @param value
     *     allowed object is
     *     {@link KadasterV2AdresLocatie }
     *     
     */
    public void setWoonlocatie(KadasterV2AdresLocatie value) {
        this.woonlocatie = value;
    }

    /**
     * Gets the value of the vermeldIn property.
     * 
     * @return
     *     possible object is
     *     {@link KadasterV2StukdeelArray }
     *     
     */
    public KadasterV2StukdeelArray getVermeldIn() {
        return vermeldIn;
    }

    /**
     * Sets the value of the vermeldIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link KadasterV2StukdeelArray }
     *     
     */
    public void setVermeldIn(KadasterV2StukdeelArray value) {
        this.vermeldIn = value;
    }

    /**
     * Gets the value of the aanvullingen property.
     * 
     * @return
     *     possible object is
     *     {@link KadasterV2AanvullingArray }
     *     
     */
    public KadasterV2AanvullingArray getAanvullingen() {
        return aanvullingen;
    }

    /**
     * Sets the value of the aanvullingen property.
     * 
     * @param value
     *     allowed object is
     *     {@link KadasterV2AanvullingArray }
     *     
     */
    public void setAanvullingen(KadasterV2AanvullingArray value) {
        this.aanvullingen = value;
    }

}
