//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.02 at 09:16:36 AM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.webservices.nl/soap/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.suggs.companydatafinderlib.companyinfo.wsdl;
